spring:
  application:
    name: demo

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.115.128:5432/postgres
    username: root
    password: 696903

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.Entity
  global-config:
    db-config:
      id-type: auto