spring:
  application:
    name: demo

#
  datasource:
    driver-class-name: org.postgresql.Driver # 显式指定 PostgreSQL 驱动
    url: jdbc:postgresql://localhost:5432/lab_db # 端口改为 5432
    username: postgres
    password: password # 替换为你在 PgAdmin 中设置的实际密码

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.entity


